# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f12be317adc6d575601b407db326294e99b43443be781ff4ce5d4ae41a11e88498b14a69330b6c95b9e7569fb7c0a8ee2935c00f496a9c3b93b302b7fbeb049f

test:
  secret_key_base: f5086c6c0628d8620922f1e92e542073e9d3615eb7d3716d1dfc7ac95edee122db79e034f032e6833ab6d8f484d5f98cb7e07e3b84be1e72c4b9692023598f01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
